sudo: required
language: bash
services:
  - docker
before_script:
  - docker -v
  - docker-compose -v
  - docker-compose build processor-move-files
script: docker-compose run --rm --entrypoint sh -e KBC_DATADIR=/code/tests/data processor-move-files /code/tests/run.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
notifications:
  slack: keboola:P2zdEpeVA18zNNYXwgM8RFWG
